# Generated by Django 5.2.17 on 2026-09-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False, 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
    ]
