# Generated by Django 5.2.17 on 2026-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id_ligne_vente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_vente', models.IntegerField()),
                ('id_produit', models.IntegerField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'lignes_vente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueCommande',
            fields=[
                ('id_vente', models.IntegerField(primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField()),
                ('id_client', models.IntegerField()),
                ('client', models.CharField(max_length=200)),
                ('employe', models.CharField(max_length=80)),
                ('statut', models.CharField(max_length=20)),
                ('nombre_produits', models.IntegerField()),
                ('quantite_totale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'vue_commandes',
                'managed': False,
            },
        ),
    ]
