# Generated by Django 5.2.17 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('contact_nom', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('adresse', models.TextField(null=True)),
                ('date_creation', models.DateTimeField()),
                ('actif', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseurs',
                'managed': False,
            },
        ),
    ]
