# Generated by Django 5.2.17 on 2026-09-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('id_fournisseur', models.IntegerField()),
                ('id_employe', models.IntegerField()),
                ('date_achat', models.DateTimeField()),
                ('statut', models.CharField(max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observation', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'db_table': 'achats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id_ligne_achat', models.AutoField(primary_key=True, serialize=False)),
                ('id_achat', models.IntegerField()),
                ('id_produit', models.IntegerField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': "Ligne d'achat",
                'verbose_name_plural': "Lignes d'achat",
                'db_table': 'lignes_achat',
                'managed': False,
            },
        ),
    ]
