# Generated by Django 5.2.17 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VueStatistiques',
            fields=[
                ('periode', models.DateField(primary_key=True, serialize=False)),
                ('nombre_ventes', models.IntegerField()),
                ('nombre_clients_distincts', models.IntegerField()),
                ('quantite_totale_vendue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=14)),
                ('panier_moyen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('marge_brute_estimee', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'vue_statistiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueTopClients',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=200)),
                ('nombre_achats', models.IntegerField()),
                ('chiffre_affaires_genere', models.DecimalField(decimal_places=2, max_digits=14)),
                ('panier_moyen', models.DecimalField(decimal_places=2, max_digits=14)),
                ('derniere_visite', models.DateTimeField()),
                ('rang', models.IntegerField()),
            ],
            options={
                'db_table': 'vue_top_clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueTopProduits',
            fields=[
                ('id_produit', models.IntegerField(primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=100)),
                ('quantite_vendue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('chiffre_affaires_genere', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rang', models.IntegerField()),
            ],
            options={
                'db_table': 'vue_top_produits',
                'managed': False,
            },
        ),
    ]
