# Generated by Django 5.2.17 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('type_paiement', models.CharField(max_length=20)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_externe', models.CharField(max_length=100, null=True)),
                ('id_employe', models.IntegerField()),
                ('date_paiement', models.DateTimeField()),
                ('observation', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaiementClient',
            fields=[
                ('id_paiement_client', models.AutoField(primary_key=True, serialize=False)),
                ('id_paiement', models.IntegerField()),
                ('id_vente', models.IntegerField()),
                ('id_client', models.IntegerField()),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Paiement client',
                'verbose_name_plural': 'Paiements clients',
                'db_table': 'paiement_client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id_paiement_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('id_paiement', models.IntegerField()),
                ('id_achat', models.IntegerField()),
                ('id_fournisseur', models.IntegerField()),
                ('montant_alloue', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'db_table': 'paiement_fournisseur',
                'managed': False,
            },
        ),
    ]
