# Generated by Django 5.2.17 on 2026-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('adresse', models.TextField(null=True)),
                ('date_inscription', models.DateTimeField()),
                ('actif', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'managed': False,
            },
        ),
    ]
