# Generated by Django 5.2.17 on 2026-08-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('id_categorie', models.IntegerField()),
                ('code_barre', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('unite_mesure', models.CharField(max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField()),
                ('date_creation', models.DateTimeField()),
            ],
            options={
                'db_table': 'produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueStock',
            fields=[
                ('id_produit', models.IntegerField(primary_key=True, serialize=False)),
                ('produit', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=100)),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_max', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_stock', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut_stock', models.CharField(max_length=20)),
                ('date_derniere_maj', models.DateTimeField()),
            ],
            options={
                'db_table': 'vue_stock',
                'managed': False,
            },
        ),
    ]
