# Generated by Django 5.2.17 on 2026-09-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id_mouvement', models.AutoField(primary_key=True, serialize=False)),
                ('id_produit', models.IntegerField()),
                ('type_mouvement', models.CharField(max_length=20)),
                ('quantite_mouvement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(max_length=20, null=True)),
                ('id_reference', models.IntegerField(null=True)),
                ('date_mouvement', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'mouvements_stock',
                'managed': False,
            },
        ),
    ]
